---
kind: pipeline
type: docker
name: Linters

concurrency:
  limit: 1

steps:
  - name: Shellcheck
    image: koalaman/shellcheck-alpine
    commands:
    - ./test/shellcheck.sh

trigger:
   event: [ pull_request, push ] 

---
kind: pipeline
type: ssh
name: default

concurrency:
  limit: 1

server:
  host:
    from_secret: server_adress
  user: 
    from_secret: username
  ssh_key: 
    from_secret: ssh_key

platform:
  os: linux
  arch: amd64
  
steps:
    - name: greeting
      commands:
      - echo "$DRONE_BRANCH" >> /root/test.txt
      - echo "$DRONE_REPO" >> /root/test.txt
