---
kind: pipeline
type: docker
name: Linters

concurrency:
  limit: 1

steps:
  - name: Shellcheck
    image: koalaman/shellcheck-alpine
    commands:
    - ./test/shellcheck.sh

trigger:
   event: [ pull_request, push ] 
