---
kind: pipeline
type: ssh
name: Ubuntu | Nginx + Apache2  

concurrency:
  limit: 1

server:
  host:
    from_secret: server_address
  user: 
    from_secret: username
  ssh_key: 
    from_secret: ssh_key

platform:
  os: linux
  arch: amd64
   
steps:
- name: Test
  commands:
  - ls ~/ -lah

trigger:
    event: [ pull_request, push ] 
