---
kind: pipeline
type: ssh
name: Test

concurrency:
  limit: 1

server:
  host:
    from_secret: dev.eris.nu
  user: 
    from_secret: root
  ssh_key: 
    from_secret: ssh_key

platform:
  os: linux
  arch: amd64
   
steps:
- name: Test
  commands:
  - echo "Jaap"; 

trigger:
  event: [ pull_request, push ]
