---
kind: pipeline
type: docker
name: shellcheck

concurrency:
  limit: 1

steps:
  - name: shellcheck
    image: koalaman/shellcheck-alpine
    commands:
    - bash ./test/shellcheck.sh
      
trigger:
   event: [ pull_request, push ] 
