---
kind: pipeline
type: docker
name: Pull Shellcheck

concurrency:
  limit: 1

steps:
  - name: shellcheck
    image: koalaman/shellcheck-alpine
    commands:
    - ./test/shellcheck.sh

trigger:
  ref:
  - refs/heads/staging/*
  - refs/heads/beta
  - refs/heads/master
  - refs/pull/*/head
