---
kind: pipeline
type: docker
name: Linting

concurrency:
  limit: 1

steps:
  - name: Shellcheck
    image: koalaman/shellcheck-alpine
    commands:
    - ./test/shellcheck.sh
  - name: PHP 8.1
    image: php:8.1-cli-bullseye
    commands:
      - ./test/check_php.sh ./web/

trigger:
   event: [ pull_request, push ] 
