---
kind: pipeline
type: docker
name: shellcheck

concurrency:
  limit: 1

steps:
  - name: shellcheck
    image: koalaman/shellcheck
    commands:
    - grep -rlE '#!/bin/(bash|sh)' ../ | grep -vE '\.(git|j2$|md$)' | sed 's|../||' | shellcheck -x  --severity="error" -e "SC2086,SC2002,SC2153,SC2181,SC2153,SC2129,SC2016,SC2196,SC1090,SC2031,SC2010,SC2143,SC2046"
      
trigger:
   event: [ pull_request, push ] 
