---
kind: pipeline
type: docker
name: shellcheck

concurrency:
  limit: 1

steps:
  - name: lint
    image: osshelp/drone-linter
    settings:
      skip_yml: true
      skip_sh: true
      skip_dockerfile: true
      skip_markdown: true
      skip_python: true
      skip_json: true
      
trigger:
   event: [ pull_request, push ] 
