---
kind: pipeline
type: ssh
name: Test

concurrency:
  limit: 1

server:
  host:
    from_secret: server_address
  user: 
    from_secret: username
  ssh_key: 
    from_secret: ssh_key

platform:
  os: linux
  arch: amd64
   
steps:
- name: Test
  commands:
  - ls /root/

trigger:
  event: [ pull_request, push ]
  ref:
  - refs/heads/staging/*
  - refs/heads/beta
  - refs/heads/release
  - refs/heads/master
  - refs/pull/*/head
